dist: xenial
sudo: required
services: docker
language: python
services:
  - docker
before_install:
  - git clone https://github.com/pulp/pulp_file.git
install:
  - pip install jmespath
  # Need /usr/bin/http script, so use sudo
  # It can mess up ownership of the python cache dir, so run it after the
  # non-sudo pip command.
  - sudo pip install httpie
  - .travis/k3s-install.sh
  - sudo wget https://github.com/operator-framework/operator-sdk/releases/download/v0.9.0/operator-sdk-v0.9.0-x86_64-linux-gnu -O /usr/local/bin/operator-sdk
  - sudo chmod +x /usr/local/bin/operator-sdk
script:
  - sudo operator-sdk build quay.io/pulp/pulp-operator:latest
  - sudo docker images
  - sudo ./up.sh
  - .travis/pulp-operator-check-and-wait.sh
  - .travis/pulp_file-tests.sh
after_failure:
  - http --timeout 30 --check-status --pretty format --print hb http://localhost:24817/pulp/api/v3/status/
  - sudo docker images
  # With the selector (which eliminates the need to look up the pod name),
  # we cannot show all logs. 10000 lines should be sufficient.
  - sudo kubectl logs -l app=pulp-api --tail=10000
  - sudo kubectl logs -l app=pulp-content --tail=10000
  - sudo kubectl logs -l app=pulp-worker --tail=10000
  - sudo kubectl logs -l app=pulp-resource-manager --tail=10000
