---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: pulp-api
  namespace: "{{ project_name }}"
  labels:
    app: pulp-api
spec:
  to:
    kind: Service
    name: pulp-api
  port:
    targetPort: pulp-api-8080
