apiVersion: pulpproject.org/v1alpha1
kind: Pulp
metadata:
  name: example-pulp
spec:
  version: latest
  pulp_api:
    replicas: 1
    log_level: INFO
  pulp_content:
    replicas: 2
    log_level: INFO
  pulp_worker:
    replicas: 2
  pulp_resource_manager:
    # Waiting on this to be implemented:
    # https://pulp.plan.io/issues/3707
    replicas: 1
