---
apiVersion: v1
kind: Service
metadata:
  name: pulp-api
  namespace: "{{ project_name }}"
  labels:
    app: pulp-api
spec:
  selector:
    app: pulp-api
  ports:
    - protocol: TCP
      targetPort: 8080
      name: pulp-api-8080
      port: 8080
