apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulp-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pulp-operator
  template:
    metadata:
      labels:
        name: pulp-operator
    spec:
      serviceAccountName: pulp-operator
      containers:
        - name: pulp-operator
          # Replace this with the built image name
          image: "{{ registry }}/pulp-operator:v0.0.1"
          imagePullPolicy: "{{ pull_policy|default('Always') }}"
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "pulp-operator"
